### ISSUE TITLE
Doesn't work and doesn't restart

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [JBarna/SpotifySaveHotkey#3]
Hello, thanks for your software which seems very useful but I can't get it to work… On first install the hotkey doesn't work and when I try to close the program and open it again, it doesn't restart (the icon disappears). I'm on Windows 10

**Comment by JBarna** [comment]
Please check out my new application that works like, a million times better than this one.
https://github.com/JBarna/SpotifyKeep
